# Set up:
library(ggplot2)
library(tidyverse)

# Creating dataframes using data.frame() object
courses <- c("ECN340", "MTH108", "CPS109", "ECN702", "ITM320")
rates <- c(9.7, 5.4, 7.8, 6.5, 8.9)

# Course Rating dataframe
d <- data.frame(courses, rates)

# Importing the housing dataframe
housing_df <- read_csv("https://www.dropbox.com/s/tvvtf9dwjufo7os/housing_train.csv?dl=1")

# Subset of housing_df to make it easier to run in console
df <- housing_df[1:6, c("SalePrice", "MSSubClass", "MSZoning", "LotFrontage")]

playground <- read_csv("https://www.dropbox.com/s/1zz4a82514avdeq/playground_injuries.csv?dl=1")

" Playground dataframe "
# We will be using Playground dataset to demonstrate some of the functionalities that can be achieved using pipes and other functions.

# Exercise:
# a. What is the max and min value in playground dataframe for age column?
max(playground$age)
min(playground$age)
# b. Does this age range make sense? (If not, filter out unusual ages and redefine the same dataset)
playground <- playground %>%
  filter(age <= 100)


# c. What are all the unique values in the age column? 
unique(playground$age)

" Modifications to dataframe "

###################################################################
# YOU WILL NOT BE EVALUATED BASED ON THIS CONCEPTS INTRODUCED BELOW
# Convert to date format
library(lubridate)

playground <- playground %>%
  mutate(treatment_date = mdy(treatment_date) )

# Add year, day, and month variables
playground <- playground %>%
  mutate(year = year(treatment_date), 
         month = month(treatment_date),
         day=day(treatment_date))
###################################################################

" groupby and summarise "

" Case Study
we would like to know the correlation between SaleType to SalePrice if there is any.

1. Data is passed via pipe
2. Data is grouped based on lgID column
3. The mean of SalePrice for each of the unique values in SaleType has been calculated

By observing the dataframe generated by running the code, we can see that the house 
where their SaleType equals New has the highest average in SalePrice. One obvious 
conclusion will be that given a house is built recently it will have a higher price 
compared to other sale types.
"


" Case Study:

Getting the frequency of different values within the Neighborhood column.

1. Group by Neighborhood column since that is our column of reference.
2. Use summarise and n()) function to get the number of repitions for different unique values within the dataframe.
3. Sort in descending order based on freq column (where we stored the frequencies)
4. Filter for the repitions of higher than 80
"



" Case Study

We would like to find out which Neghbourhoods have the most repetitions 
(they are repeated in entries of Neighborhood column).

1. Follow the same process as the previous code.
2. Filter the entries where freq > 80, meaning there have more than 80 entries 
(rows) where a certain value in Neighbourhood has been repeated.
"



" Case Study: 
Which playground equipment causes the most injuries?
  
  1. We have to specify our column of interest by group_by
  2. Use summarize to count the number of occurances
  3. Use arrange to list the products in a descending order
  4. Filter and keep repitions of greater than 1000
"



# Exercise: What if we wanted the relative frequency? 
# (Hint: sum of all the values should equal 1)

# Plotting the relative frequency of products
playground %>% 
  group_by(product) %>% 
  summarise(freq=n()) %>% 
  ggplot(aes(x=reorder(product, -freq), y=freq, fill=product)) +
    geom_bar(stat="identity") +
    theme_classic() +
    theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5)) + 
    labs(
      x="Products",
      y="Relative Frequency",
      title=paste("Relative Frequency Bar Chart")
    ) 

# Exercise: What percentage of people who hurt themselves with Slides, hurt their heads?
# 1. Filter data by slides
# 2. Calculate the relative frequency of the data
# 3. Choose the entries with injury == HEAD


View(playground)

# Exercise : What playground equipment causes the most dislocations?
# 1. Filter by injury_label of dislocation
# 2. Make a column to count the number dislocations for each product
# 3. Sort in the descending order 


# Exercise: What playground injury is most common for people over 30 years old?
# 1. Filter by age being bigger than 30
# 2. Count the number for each injury
# 3. Sort in the descending order



housing_df <- read_csv("https://www.dropbox.com/s/tvvtf9dwjufo7os/housing_train.csv?dl=1")

# Exercise: What is the average SalePrice for each unique value in Alley column?


# And what is the maximum value of LotFrontage for each unique value in Alley?


# Exercise: Exercise: What is the maximum SalePrice for each unique value in Alley column?
# And what is the most repeated value of OverQual for each unique value in Alley?


# Exercise: Get the mean price and mode of OverQual for each of the unique values
# in Alley then sort in descending order based on Average SalePrice


